# Generated by Django 2.2.2 on 2021-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
                ('device_description', models.CharField(max_length=200)),
            ],
        ),
    ]
